# Place your local configuration in /etc/mosquitto/conf.d/
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf.example

per_listener_settings true
pid_file ./mosq/mosquitto.pid
persistence false
log_dest file ./mosq/mosquitto.log

listener 9368
allow_anonymous false
password_file ./mosq/pwfile

cafile ./mosq/ca.crt
certfile ./mosq/server.crt
keyfile ./mosq/server.key
tls_version tlsv1.2
